### PR TITLE
Xform2d

### PR DESCRIPTION
**Pull request by tanguyduval**
Just found a bug.
Crash when using nii_xform on MxNx1xT volumes (2D but multiple volumes). Now using interp2.

### CODE REVIEW

**Comment by xiangruili** [comment]
@tanguyduval 
Before merging the request, I wonder if there is a better/cleaner way to deal with these special cases. A possible solution is to `repmat` the image at dimension with insufficient data, and get the needed data after `interp`/`smooth` using `builtin` function.

**Comment by tanguyduval** [comment]
@xiangruili ok done.
Note that with this method, the interpolation is "nearest" and not linear...

**Comment by xiangruili** [comment]
I noticed we are padding `missVal`, which is often 0 or nan. Maybe it is better to `repmat` data? If so, there may be unnecessary to change 'linear' to 'nearest' for the special case?

**Comment by tanguyduval** [comment]
@xiangruili Just did the modification by repmat by 3 slices. Just tested and this way it works. I had to increment the grid `I` to interpolate in the middle slice.

**Comment by xiangruili** [comment]
@tanguyduval I was just discussing if `repmat` is good, and you already did it :)
Let's think a little bit to make sure 'repmat' won't cause problem before merging. Thank you for your work.

**Comment by tanguyduval** [comment]
Indeed, edge effects with repmat will occur for 2D reslice on 3D volumes... I solved this with 
e8104f5
I tested on my data (2D --> 3D, 2D --> 2D).

**Pull request merged**
